### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by NemoAlex** [panteng/vue-pikaday#1]
It would be nice to have the ability to use npm for the version control.

**Comment by panteng** [comment]
Thanks. I will publish it to npm later.
For now, you can use `npm install panteng/vue-pikaday` to install this project.

**Comment by simonj** [comment]
Hey, thanks for a nice plugin, i just have some issues getting to use it :(

i have installed it with the npm install panteng/vue-pikaday but I'm not sure how i require it

i have tried with `Vue.directive('pikaday', require('pikaday'));`

**Comment by panteng** [comment]
@SimonJ I suggest you just copy my file ./src/directives/pikaday.js into your project and treat this file as your own hand-write code because you can make some changes on your own need, like custom options for pikaday.

If you really want to use this vue-pikaday with npm, you can try `Vue.directive('pikaday', require('vue-pikaday/src/directives/pikaday'));`.

I'm not sure but I think this should work. But in this way, you cannot set your own custom options on pikaday any more.
