### ISSUE TITLE
Use element directive

### ISSUE THREAD

**Issue by NemoAlex** [panteng/vue-pikaday#2]
How about use element directive like this:

```
<pickaday class="form-control" id="pickStartDate" placeholder="Pick a date">
```

compile to 

```
<input type="text" class="form-control" id="pickStartDate" placeholder="Pick a date">
```

with automatic pickaday binding.
And the default value can be assigned by `value` property.

**Comment by panteng** [comment]
I have thought about this for a while.
Using element directive means the `pikaday` directive has to create an `input` element by itself. I don't think this is a good practice. 
Because each time the `pikaday` directive is compiled, it has to determine whether we are using it as a normal directive or as an element directive. It just makes things more complicated.
There's another way to do this - by using Component. We can define a component called `pikaday` which compiles to:

```
<input type="text" v-pikaday>
```

Then we can use `<pikaday></pikaday>` in our HTML.

**Comment by NemoAlex** [comment]
Why not just remove normal directive, and using element directive to instead?

**Comment by panteng** [comment]
It's more like a personal preference.
Because when I see `<pikaday></pikaday>` in my HTML, I may be confused about whether it is a directive or a component. However, if I see `<input v-pikaday>`, I will immediately understand that this is an `input` element which is operated by a directive called `pikaday`. So I can just go to my directive folder and find this directive and edit it. This is more convenient.

**Comment by NemoAlex** [comment]
It's a common way to do like this.
Anyway, please take this as a proposal and think about it later.
I believe you'll get used to it : )

**Comment by panteng** [comment]
Ok, I'm still learning Vue.js.
Thanks for your advice.
